name: Build extension

on:
  push:
    tags:
      - "*.*.*"
    paths:
      - 'tmbundle/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '>=20.x.x'
    
    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Package .vsix
      run: cd tmbundle && vsce package

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: tmbundle/*.vsix